version: 1.00.00-{build}

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64

install:
  - git submodule update --init --recursive

before_build:
  - md c:\projects\milkytracker\build
  - cd c:\projects\milkytracker\build
  - if %platform% == Win32 cmake -G "Visual Studio 14" -T v140_xp ..
  - if %platform% == x64 cmake -G "Visual Studio 14 Win64" -T v140_xp ..

build:
    project: c:\projects\milkytracker\build\MilkyTracker.sln

after_build:
  # https://github.com/chocolatey/chocolatey/issues/431
  - cmake -E remove -f c:\programdata\chocolatey\bin\cpack.exe
  - cpack -C %configuration%

artifacts:
  - path: build\milkytracker*.zip

deploy:
  description: "Release v$(appveyor_build_version)"
  provider: GitHub
  auth_token:
    secure: 6nhDGNy5r2eMA4/do85rPE2KB20B8iCcr8pqj990eGC1jIKGF15ZM611ybqoqM3N
  artifact: /\/build\/milkytracker.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: appveyor
    #appveyor_repo_tag: true        # deploy on tag push only
